---
title: "PML_PA"
author: "Aneesh Sathe"
date: "June 13, 2015"
output: html_document
---

```{r load libraries}
library(data.table)
library(ggplot2)
library(caret)
library(doParallel)
```
 



```{r Read Data, cache=TRUE}

pro_in_dat=read.csv("pml-training.csv",nrows =2)
head(pro_in_dat)

keywords=c("X","user_name","min","max","amplitude","window","kurtosis","user","*timestamp*","*skewness*","var","avg","stddev")
strings=colnames(pro_in_dat)
# colnames(pro_in_dat)[!apply(sapply(keywords, grepl, strings, ignore.case=TRUE),1,any)]

mat=apply(sapply(keywords, grepl, strings, ignore.case=TRUE),1,any)
mat[mat]="NULL"
mat[mat==FALSE]=NA


pro_in_dat=read.csv("pml-training.csv",colClasses = mat)
levels(pro_in_dat$classe)
```

```{r}
inTrain <- createDataPartition(y=pro_in_dat$classe,p=0.7, list=FALSE)
training <- pro_in_dat[inTrain,]
# pred_training <- pro_in_dat[inTrain,41]
testing <- pro_in_dat[-inTrain,]
# pred_test <- pro_in_dat[inTrain,41]
```


```{r}
library(GGally)
ggpairs(pro_in_dat,colour='classe')
```



```{r CenterScale}
CS_dat=preProcess(pro_in_dat[,1:40], method=c("center", "scale"))
```


```{r PCA}
pr=prcomp(pro_in_dat[,1:40])
#### TO DETERMINE WHICH PC TO USE
screeplot(pr,type="lines")
```

```{r PCAGraph}
typeColor <- ((pro_in_dat$classe=="A")*1 + 1)
plot(pr$x[,2],pr$x[,3],col=typeColor,xlab="PC1",ylab="PC2")
```

```{r ZeroVar}
nearZeroVar(pro_in_dat[,1:40],saveMetrics=TRUE)
```
```{r}
qplot(magnet,colour=classe,data=pro_in_dat,geom = "density")
```



```{r RandomForest}
cl <- makePSOCKcluster(2)
registerDoParallel(cl)
ctrl <- trainControl(preProcOptions = list(pcaComp=4))
modFit=train(classe~.,data=training, method="rf",prox=TRUE,preProcess=c("pca"),trControl = ctrl)
stopCluster(cl)
modFit

```





































You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases. 